local t = require("tests.harness")
t.bootstrap()

local panel = require("utils.bottom_panel")
local registry = require("utils.task_registry")

local function isolated(fn)
  local old_tab = vim.api.nvim_get_current_tabpage()
  local old_qf = vim.fn.getqflist({ items = 0, title = 0, idx = 0 })
  local old_buffers = {}
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do old_buffers[buf] = true end
  panel._reset_for_test()
  registry._reset_for_test()
  vim.cmd("tabnew")
  local tab = vim.api.nvim_get_current_tabpage()
  local ok, err = pcall(fn, tab)
  if vim.api.nvim_tabpage_is_valid(tab) then
    vim.api.nvim_set_current_tabpage(tab)
    vim.cmd("tabclose!")
  end
  if vim.api.nvim_tabpage_is_valid(old_tab) then vim.api.nvim_set_current_tabpage(old_tab) end
  vim.fn.setqflist({}, "r", old_qf)
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if not old_buffers[buf] then pcall(vim.api.nvim_buf_delete, buf, { force = true }) end
  end
  panel._reset_for_test()
  registry._reset_for_test()
  if not ok then error(err, 0) end
end

local function buffer(lines)
  local buf = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines or { "output" })
  return buf
end

local function lines(buf)
  return table.concat(vim.api.nvim_buf_get_lines(buf, 0, -1, false), "\n")
end

local function mapped(buf, lhs)
  for _, map in ipairs(vim.api.nvim_buf_get_keymap(buf, "n")) do
    if map.lhs == lhs then return map.callback end
  end
  error("missing buffer key " .. lhs)
end

t.describe("android_ide_bottom_panel: 真实窗口与内容切换", function()
  t.it("四种面板连续两圈只有一个 host，保留构建输出", function()
    isolated(function(tab)
      vim.fn.setqflist({}, "r")
      local build, logcat = buffer({ "build completed" }), buffer({ "device output" })
      panel.register("build", build)
      panel.register("logcat", logcat)
      local host = panel.show("build")
      local expected = { "quickfix", "logcat", "tasks", "build", "quickfix", "logcat", "tasks", "build" }
      for _, kind in ipairs(expected) do
        t.assert_eq(panel.cycle(), host, "切换 " .. kind .. " 应复用原 window id")
        t.assert_eq(#vim.api.nvim_tabpage_list_wins(tab), 2)
        t.assert_eq(vim.b[vim.api.nvim_win_get_buf(host)].ue_bottom_panel_kind, kind)
      end
      t.assert_eq(vim.api.nvim_win_get_buf(host), build)
      t.assert_contains(lines(build), "build completed")
      t.assert_true(vim.api.nvim_buf_is_valid(logcat))
      t.assert_eq(vim.bo[build].bufhidden, "hide")
    end)
  end)

  t.it("空 logcat 明确告知未启动，循环不调用进程 API", function()
    isolated(function()
      vim.fn.setqflist({}, "r")
      local jobstart, system = vim.fn.jobstart, vim.system
      vim.fn.jobstart = function() error("cycle must not start a job") end
      vim.system = function() error("cycle must not start a process") end
      local ok, err = pcall(function()
        for _ = 1, 8 do panel.cycle() end
        local host = panel.show("logcat")
        local text = lines(vim.api.nvim_win_get_buf(host))
        t.assert_contains(text, "尚未启动 Logcat")
        t.assert_contains(text, "<leader>ug 或 d4")
      end)
      vim.fn.jobstart, vim.system = jobstart, system
      if not ok then error(err, 0) end
    end)
  end)

  t.it("采用现有底部窗口并合并重复面板，不关闭代码或浮窗", function()
    isolated(function(tab)
      local code = vim.api.nvim_get_current_win()
      local build, logcat = buffer(), buffer()
      panel.register("build", build)
      panel.register("logcat", logcat)
      local first = vim.api.nvim_open_win(build, false, { split = "below", win = -1, height = 4 })
      local second = vim.api.nvim_open_win(logcat, false, { split = "below", win = -1, height = 4 })
      local float = vim.api.nvim_open_win(build, false, { relative = "editor", row = 1, col = 1, width = 20, height = 2 })
      t.assert_eq(panel.show("build"), second)
      t.assert_false(vim.api.nvim_win_is_valid(first))
      t.assert_true(vim.api.nvim_win_is_valid(code))
      t.assert_true(vim.api.nvim_win_is_valid(float))
      t.assert_eq(#vim.api.nvim_tabpage_list_wins(tab), 3)
    end)
  end)

  t.it("debug 共用 host 但不加入四面板循环", function()
    isolated(function(tab)
      local host = panel.show("build", buffer())
      t.assert_eq(panel.show("debug", buffer({ "repl" })), host)
      t.assert_eq(panel.cycle(), host)
      t.assert_eq(vim.b[vim.api.nvim_win_get_buf(host)].ue_bottom_panel_kind, "build")
      t.assert_eq(#vim.api.nvim_tabpage_list_wins(tab), 2)
    end)
  end)

  t.it("原生 quickfix 回车跳源，并在现有 host 中显示", function()
    isolated(function(tab)
      local source = buffer({ "first", "second", "target" })
      local code = vim.api.nvim_get_current_win()
      vim.api.nvim_win_set_buf(code, source)
      local host = panel.show("build", buffer())
      vim.fn.setqflist({}, "r", { title = "build", items = { { bufnr = source, lnum = 3, col = 1, text = "broken", type = "E" } } })
      t.assert_eq(panel.show("quickfix"), host)
      t.assert_eq(vim.bo[vim.api.nvim_win_get_buf(host)].buftype, "quickfix")
      t.assert_eq(#vim.api.nvim_tabpage_list_wins(tab), 2)
      vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<CR>", true, false, true), "xt", false)
      t.assert_eq(vim.api.nvim_get_current_buf(), source)
      t.assert_eq(vim.api.nvim_win_get_cursor(0)[1], 3)
      t.assert_true(vim.api.nvim_win_is_valid(host))
    end)
  end)

  t.it("多 tab host 隔离，另一个 tab 的内容与窗口不受影响", function()
    isolated(function(tab)
      local build = buffer({ "first tab" })
      local first = panel.show("build", build)
      vim.cmd("tabnew")
      local other = vim.api.nvim_get_current_tabpage()
      local ok, err = pcall(function()
        t.assert_nil(panel.window())
        local second = panel.show("logcat", buffer({ "second tab" }))
        t.assert_true(first ~= second)
        panel.cycle()
        t.assert_eq(vim.api.nvim_win_get_buf(first), build)
        t.assert_true(vim.api.nvim_win_is_valid(first))
        vim.api.nvim_set_current_tabpage(tab)
        t.assert_eq(panel.window(), first)
        panel.cycle()
        t.assert_true(vim.api.nvim_win_is_valid(second))
      end)
      vim.api.nvim_set_current_tabpage(other)
      vim.cmd("tabclose!")
      vim.api.nvim_set_current_tabpage(tab)
      if not ok then error(err, 0) end
    end)
  end)

  t.it("手动关窗后能重建，focus=false 保留代码窗口焦点", function()
    isolated(function(tab)
      local code = vim.api.nvim_get_current_win()
      local build = buffer()
      local host = panel.show("build", build, { focus = false, height = 5 })
      t.assert_eq(vim.api.nvim_get_current_win(), code)
      t.assert_eq(vim.api.nvim_win_get_height(host), 5)
      vim.api.nvim_win_close(host, true)
      t.assert_nil(panel.window())
      t.assert_true(vim.api.nvim_buf_is_valid(build))
      local recreated = panel.show("build", nil, { focus = false })
      t.assert_true(recreated ~= host)
      t.assert_eq(vim.api.nvim_win_get_buf(recreated), build)
      t.assert_eq(vim.api.nvim_get_current_win(), code)
      t.assert_eq(#vim.api.nvim_tabpage_list_wins(tab), 2)
    end)
  end)

  t.it("切换恢复各 buffer 的 cursor/view，后台追加行不会丢失浏览位置", function()
    isolated(function()
      local content = {}
      for i = 1, 100 do content[i] = "output " .. i end
      local build, logcat = buffer(content), buffer(content)
      panel.register("logcat", logcat)
      local host = panel.show("build", build, { height = 6 })
      vim.fn.winrestview({ lnum = 43, col = 4, topline = 41 })
      local build_view = vim.fn.winsaveview()
      panel.show("logcat")
      vim.fn.winrestview({ lnum = 12, col = 2, topline = 10 })
      local log_view = vim.fn.winsaveview()
      vim.api.nvim_buf_set_lines(build, -1, -1, false, { "later output" })
      panel.show("build")
      local restored = vim.fn.winsaveview()
      t.assert_eq(restored.lnum, build_view.lnum)
      t.assert_eq(restored.col, build_view.col)
      t.assert_eq(restored.topline, build_view.topline)
      panel.show("logcat")
      t.assert_eq(vim.fn.winsaveview().lnum, log_view.lnum)
      t.assert_eq(vim.api.nvim_win_get_buf(host), logcat)
    end)
  end)

  t.it("remove 只作用于相同 reader，删除 stale buffer 后显示占位", function()
    isolated(function()
      local old, current = buffer(), buffer()
      panel.register("logcat", old)
      local host = panel.show("logcat", current)
      t.assert_false(panel.remove("logcat", nil))
      t.assert_eq(vim.api.nvim_win_get_buf(host), current)
      t.assert_false(panel.remove("logcat", old))
      t.assert_eq(vim.api.nvim_win_get_buf(host), current)
      t.assert_true(panel.remove("logcat", current))
      t.assert_contains(lines(vim.api.nvim_win_get_buf(host)), "尚未启动 Logcat")
      t.assert_true(vim.api.nvim_buf_is_valid(current))
      local stale = buffer()
      panel.register("build", stale)
      vim.api.nvim_buf_delete(stale, { force = true })
      panel.show("build")
      t.assert_contains(lines(vim.api.nvim_win_get_buf(host)), "尚无构建输出")
    end)
  end)

  t.it("隐藏 live 终端不终止进程，退出后可重新显示同一 buffer", function()
    isolated(function()
      local buf = buffer({ "" })
      vim.bo[buf].modified = false
      local job
      vim.api.nvim_buf_call(buf, function()
        job = vim.fn.jobstart({ vim.v.progpath, "--headless", "-u", "NONE", "-i", "NONE", "-c", "sleep 500m", "-c", "qa!" }, { term = true })
      end)
      t.assert_true(job > 0)
      local ok, err = pcall(function()
        local host = panel.show("build", buf)
        panel.show("tasks")
        t.assert_eq(vim.fn.jobwait({ job }, 0)[1], -1)
        t.assert_true(vim.api.nvim_buf_is_valid(buf))
        t.assert_true(vim.wait(3000, function() return vim.fn.jobwait({ job }, 0)[1] ~= -1 end, 20))
        t.assert_eq(panel.show("build"), host)
        t.assert_eq(vim.api.nvim_win_get_buf(host), buf)
        t.assert_eq(vim.bo[buf].buftype, "terminal")
      end)
      pcall(vim.fn.jobstop, job)
      if not ok then error(err, 0) end
    end)
  end)

  t.it("外部建终端后 register 识别 host；切换清理调试窗口局部选项", function()
    isolated(function()
      local host = panel.show("debug")
      local build = buffer()
      vim.api.nvim_win_set_buf(host, build)
      panel.register("build", build)
      t.assert_eq(panel.window(), host)
      vim.wo[host].statusline, vim.wo[host].winbar = "debug tabs", "debug header"
      vim.wo[host].number, vim.wo[host].wrap = true, true
      panel.cycle()
      t.assert_eq(vim.b[vim.api.nvim_win_get_buf(host)].ue_bottom_panel_kind, "quickfix")
      t.assert_contains(vim.wo[host].statusline, "[问题]")
      t.assert_false(vim.wo[host].statusline:find("debug tabs", 1, true) ~= nil)
      t.assert_eq(vim.wo[host].winbar, "")
      t.assert_false(vim.wo[host].number)
      t.assert_false(vim.wo[host].wrap)
    end)
  end)

  t.it("用户把旧 host 换成代码后，不关闭或覆盖该代码窗口", function()
    isolated(function(tab)
      local old = panel.show("build", buffer())
      local code = buffer({ "int main() {}" })
      vim.api.nvim_win_set_buf(old, code)
      t.assert_nil(panel.window())
      local host = panel.show("tasks")
      t.assert_true(host ~= old)
      t.assert_true(vim.api.nvim_win_is_valid(old))
      t.assert_eq(vim.api.nvim_win_get_buf(old), code)
      t.assert_eq(#vim.api.nvim_tabpage_list_wins(tab), 3)
    end)
  end)

  t.it("任务面板查询派生状态，dd 停止真实 registry 记录且无二次确认", function()
    isolated(function()
      registry._set_probe_for_test(function(rec) return rec.handle.alive and "running" or "done" end)
      local handle = { alive = true, killed = 0 }
      function handle:kill() self.alive = false; self.killed = self.killed + 1 end
      local id = registry.register({ name = "compile", kind = "system", handle = handle })
      local host = panel.show("tasks")
      local buf = vim.api.nvim_win_get_buf(host)
      t.assert_contains(lines(buf), tostring(id))
      t.assert_contains(lines(buf), "running")
      t.assert_contains(lines(buf), "compile")
      vim.api.nvim_win_set_cursor(host, { 3, 0 })
      mapped(buf, "dd")()
      t.assert_eq(handle.killed, 1)
      t.assert_eq(registry.status(id), "cancelled")
      t.assert_contains(lines(buf), "cancelled")
      t.assert_nil(registry.get(id).state)
      mapped(buf, "<CR>")()
      t.assert_eq(handle.killed, 1)
      handle.alive = true
      mapped(buf, "r")()
      t.assert_contains(lines(buf), "running")
    end)
  end)

  t.it("命令可重复设置，并选择相同 host 的内容", function()
    isolated(function()
      panel.setup_commands()
      panel.setup_commands()
      vim.cmd("UEPanel build")
      local host = panel.window()
      vim.cmd("UEPanelNext")
      t.assert_eq(panel.window(), host)
      t.assert_eq(vim.b[vim.api.nvim_win_get_buf(host)].ue_bottom_panel_kind, "quickfix")
      vim.cmd("UEPanel tasks")
      t.assert_eq(panel.window(), host)
    end)
  end)
end)
