local t = require('tests.harness')
t.bootstrap()
local values = require('ue.dap._ue_values')
local formatters = require('ue.dap._ue_formatters')

local function session_with(items, handler)
  local calls = {}
  local session = {current_frame = {id = 42}}
  session.request = function(_, command, args, callback)
    calls[#calls + 1] = {command = command, args = args}
    if command == 'variables' then callback(nil, {variables = items})
    elseif handler then handler(command, args, callback)
    elseif callback then callback(nil, {}) end
    return #calls
  end
  values.install(session)
  return session, calls
end

t.describe('UE native DAP values', function()
  t.it('empty FString remains expandable and does not read NULL', function()
    local input = {{type = 'FString', value = 'storage=0 data=0x00000000', variablesReference = 9}}
    local session, calls = session_with(input)
    session:request('variables', {variablesReference = 1}, function(err, body)
      t.assert_eq(err, nil)
      t.assert_eq(body.variables[1].value, '"" (empty)')
      t.assert_eq(body.variables[1].variablesReference, 9)
    end)
    t.assert_eq(#calls, 1)
    t.assert_eq(input[1].value, 'storage=0 data=0x00000000')
  end)

  t.it('UTF16 reads decode Chinese and surrogate pairs without calling the target', function()
    local utf16 = string.char(0x55, 0, 0x03, 0x8c, 0x3c, 0xd8, 0xae, 0xdf, 0, 0)
    local session, calls = session_with({{type = 'FString', value = 'storage=5 data=0x1234'}}, function(command, args, callback)
      t.assert_eq(command, 'readMemory')
      t.assert_eq(args.count, 10)
      t.assert_eq(args.memoryReference, '0x1234')
      callback(nil, {data = vim.base64.encode(utf16)})
    end)
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].value, '"U调🎮"')
    end)
    t.assert_eq(#calls, 2)
  end)

  t.it('unreadable and partial strings are reported, not presented as empty', function()
    local session = session_with({{type = 'FString', value = 'storage=3 data=0x1234'}}, function(_, _, callback)
      callback(nil, {data = vim.base64.encode('AB'), unreadableBytes = 4})
    end)
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_contains(body.variables[1].value, '<unreadable FString>')
    end)
    t.assert_eq(values.utf16(string.char(0, 0xd8)), '�')
  end)

  t.it('large strings have bounded reads and explicit truncation', function()
    local session = session_with({{type = 'FString', value = 'storage=1000 data=0x1234'}}, function(_, args, callback)
      t.assert_eq(args.count, 512)
      callback(nil, {data = vim.base64.encode(string.rep('A\0', 256))})
    end)
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_contains(body.variables[1].value, '(truncated)')
    end)
  end)

  t.it('sparse containers subtract freed slots', function()
    local session = session_with({{type = 'TMap<int, int>', value = 'slots=7 free=3'}, {type = 'TSet<int>', value = 'slots=0 free=0'}})
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].value, 'Num=4')
      t.assert_eq(body.variables[2].value, 'Num=0')
    end)
  end)

  t.it('TArray elements read real memory and retain native raw fields/references', function()
    local items = {{type = 'TArray<int, Allocator>', value = 'size=3 cap=8 data=0x1234', variablesReference = 10}}
    local session = session_with(items, function(command, args, callback)
      t.assert_eq(command, 'readMemory')
      t.assert_eq(args.memoryReference, '0x1234')
      t.assert_eq(args.count, 12)
      callback(nil, {data = vim.base64.encode(string.char(11,0,0,0,22,0,0,0,33,0,0,0))})
    end)
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].variablesReference, 10)
      t.assert_eq(body.variables[1].indexedVariables, 3)
    end)
    session:request('variables', {variablesReference = 10}, function(_, body)
      t.assert_eq(body.variables[1].name, '[0]')
      t.assert_eq(body.variables[1].value, '11')
      t.assert_eq(body.variables[3].value, '33')
      t.assert_eq(body.variables[4].variablesReference, 10)
    end)
  end)

  t.it('empty arrays do not dereference storage, even with allocated capacity', function()
    local session, calls = session_with({{type = 'TArray<int>', value = 'size=0 cap=8 data=0x1234', variablesReference = 9}})
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].variablesReference, 0)
    end)
    t.assert_eq(#calls, 1)
  end)

  t.it('FString Data typedef exposes its real UTF16 TArray elements', function()
    t.assert_eq(values.array_element('FString::DataType'), 'char16_t')
    local session = session_with({{type = 'FString::DataType', value = 'size=3 cap=3 data=0x1234', variablesReference = 10}}, function(command, args, callback)
      t.assert_eq(command, 'readMemory')
      t.assert_eq(args.count, 6)
      callback(nil, {data = vim.base64.encode('A\0B\0\0\0')})
    end)
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].indexedVariables, 3)
      t.assert_eq(body.variables[1].variablesReference, 10)
    end)
    session:request('variables', {variablesReference = 10, filter = 'indexed'}, function(_, body)
      t.assert_eq(#body.variables, 3)
      t.assert_eq(body.variables[1].value, '"A"')
    end)
  end)

  t.it('NULL UObject pointers are explicit and cannot expand invalid members', function()
    local session = session_with({{type = 'UObject *', value = '0x0000000000000000', variablesReference = 9}})
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].value, 'NULL')
      t.assert_eq(body.variables[1].variablesReference, 0)
    end)
  end)

  t.it('bounded arrays expose truncation and unknown element layouts keep raw children', function()
    local session = session_with({{type = 'TArray<int>', value = 'size=200 cap=200 data=0x1234', variablesReference = 9}})
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].indexedVariables, 128)
      t.assert_contains(body.variables[1].value, 'first 128 of 200')
    end)
    local unknown = session_with({{type = 'TArray<Unknown>', value = 'size=3 cap=3 data=0x1234', variablesReference = 9}})
    unknown:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].variablesReference, 9)
      t.assert_contains(body.variables[1].value, 'elements unavailable; raw fields retained')
    end)
  end)

  t.it('shared pointer NULL and parent errors do not become valid values', function()
    local session = session_with({{type = 'TSharedPtr<UObject>', value = 'obj=0x0000'}, {type = 'TSharedPtr<UObject>', value = 'obj=0x1234'}, {type = 'FString', value = '<error: parent is NULL>'}})
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].value, 'NULL obj=0x0000')
      t.assert_eq(body.variables[2].value, 'valid obj=0x1234')
      t.assert_eq(body.variables[3].value, '<error: parent is NULL>')
    end)
  end)

  t.it('weak pointers never infer live validity from a positive index and serial', function()
    local session, calls = session_with({{type = 'TWeakObjectPtr<UObject>', value = 'idx=65538 serial=4'}, {type = 'TWeakObjectPtr<UObject>', value = 'idx=-1 serial=0'}})
    session:request('variables', {variablesReference = 1}, function(_, body)
      t.assert_eq(body.variables[1].value, 'validity unverified idx=65538 serial=4')
      t.assert_eq(body.variables[2].value, 'NULL idx=-1 serial=0')
    end)
    t.assert_eq(#calls, 1)
  end)

  t.it('array address and pointer decoding preserve all 64 bits', function()
    local array = require('ue.dap._ue_array')
    t.assert_eq(array.address('0xf123456789abcdef', 32), '0xf123456789abce0f')
    t.assert_eq(array.hex(string.char(0xef,0xcd,0xab,0x89,0x67,0x45,0x23,0xf1)), '0xf123456789abcdef')
    t.assert_eq(array.size('Unknown'), nil)
  end)

  t.it('continue discards pending enrichment from the previous stop', function()
    local finish_read, result
    local input = {{type = 'FString', value = 'storage=2 data=0x1234'}}
    local session = session_with(input, function(command, _, callback)
      if command == 'readMemory' then finish_read = callback elseif callback then callback(nil, {}) end
    end)
    session:request('variables', {variablesReference = 1}, function(_, body) result = body end)
    session:request('continue', {})
    finish_read(nil, {data = vim.base64.encode('A\0\0\0')})
    t.assert_eq(result.variables[1].value, input[1].value)
  end)

  t.it('formatter import is non-fatal and fallback exists independently of Python', function()
    local commands = formatters.commands(nil, 'missing/formatter.py')
    local text = table.concat(commands, '\n')
    t.assert_contains(text, 'Number=${var.Number}')
    t.assert_contains(text, 'NumFreeIndices')
    t.assert_contains(text, 'type category enable UEFallback')
    t.assert_false(text:find('command script import', 1, true) ~= nil)
    local path = vim.fn.tempname() .. '.py'
    vim.fn.writefile({'# formatter fixture'}, path)
    commands = formatters.commands(nil, path)
    vim.fn.delete(path)
    t.assert_contains(commands[#commands], '?command script import')
    for _, command in ipairs(commands) do t.assert_false(command:match('^%??script%s') ~= nil) end
  end)
end)
