local t = require("tests.harness")
t.bootstrap()
local fixture = require("tests.helpers.git_review_fixture")
local plugin = vim.fn.stdpath("data") .. "/lazy/codediff.nvim"
if vim.fn.isdirectory(plugin) == 0 or vim.fn.executable("git") ~= 1 then
  t.skip("git review native action safety", "CodeDiff checkout or Git unavailable", { native = true })
  return
end
vim.opt.rtp:append(plugin)
local replacement = { original = { start_line = 1, end_line = 2 }, modified = { start_line = 1, end_line = 2 } }
local function install()
  t.assert_true(require("workarounds.codediff.safe_mutations").apply())
end
local function await(f)
  t.assert_true(vim.wait(5000, function() return #f.messages > 0 and f.idle() end, 10), "action completed")
end

t.describe("git review safety", function()
  t.it("upstream discard reproducer: unrelated dirty lines are implicitly saved", function()
    fixture.with_repo(function(f)
      f.baseline("old\nkeep\n")
      f.write("new\nkeep\n")
      fixture.with_actions(f, "old\nkeep\n", f.read(), { replacement }, function(actions, ctx, _, _, b)
        vim.api.nvim_buf_set_lines(b, 1, 2, false, { "UNSAVED" })
        actions.discard_hunk(ctx)
        t.assert_eq(f.read(), "old\nUNSAVED\n")
        t.assert_false(vim.bo[b].modified)
      end)
    end)
  end)
  t.it("upstream insertion reproducer: stale index accepts a zero-context patch", function()
    fixture.with_repo(function(f)
      f.baseline("base\n")
      f.write("insert\nbase\n")
      fixture.with_actions(f, "base\n", f.read(), {
        { original = { start_line = 1, end_line = 1 }, modified = { start_line = 1, end_line = 2 } },
      }, function(actions, ctx)
        f.write("external\nbase\n")
        f.git({ "add", "--", f.path })
        actions.stage_hunk(ctx)
        t.assert_true(vim.wait(5000, function() return #f.messages > 0 end, 10))
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "insert\nexternal\nbase\n")
      end)
    end)
  end)
  t.it("guard rejects dirty discard without saving or changing index", function()
    fixture.with_repo(function(f)
      f.baseline("old\nkeep\n")
      f.write("new\nkeep\n")
      fixture.with_actions(f, "old\nkeep\n", f.read(), { replacement }, function(actions, ctx, _, _, b)
        install()
        vim.api.nvim_buf_set_lines(b, 1, 2, false, { "UNSAVED" })
        actions.discard_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Unsaved buffer")
        t.assert_eq(f.read(), "new\nkeep\n")
        t.assert_true(vim.bo[b].modified)
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\nkeep\n")
      end)
    end)
  end)
  t.it("guard rejects a stale pure insertion and preserves external index", function()
    fixture.with_repo(function(f)
      f.baseline("base\n")
      f.write("insert\nbase\n")
      fixture.with_actions(f, "base\n", f.read(), {
        { original = { start_line = 1, end_line = 1 }, modified = { start_line = 1, end_line = 2 } },
      }, function(actions, ctx)
        install()
        f.write("external\nbase\n")
        f.git({ "add", "--", f.path })
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Index changed")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "external\nbase\n")
      end)
    end)
  end)
  for _, eol in ipairs({ "\n", "\r\n" }) do
    t.it("native stage/unstage preserves " .. (eol == "\n" and "LF" or "CRLF") .. " and unselected hunk", function()
      fixture.with_repo(function(f)
        f.path = "space 中文.txt"
        local base = "old" .. eol .. "keep" .. eol .. "tail" .. eol
        local work = "new" .. eol .. "keep" .. eol .. "other" .. eol
        f.baseline(base)
        f.write(work)
        fixture.with_actions(f, base, work, { replacement }, function(actions, ctx)
          install()
          actions.stage_hunk(ctx)
          await(f)
          t.assert_contains(f.messages[1], "Staged hunk")
          t.assert_true(f.refreshes[1].index)
          t.assert_eq(f.git({ "show", ":0:" .. f.path }), "new" .. eol .. "keep" .. eol .. "tail" .. eol)
          t.assert_eq(f.read(), work)
        end)
        fixture.with_actions(f, base, "new" .. eol .. "keep" .. eol .. "tail" .. eol, { replacement }, function(actions, ctx, session)
          session.original_revision, session.modified_revision = "HEAD", ":0"
          install()
          actions.unstage_hunk(ctx)
          await(f)
          t.assert_contains(f.messages[1], "Unstaged hunk")
          t.assert_eq(f.git({ "show", ":0:" .. f.path }), base)
          t.assert_eq(f.read(), work)
        end)
      end)
    end)
  end
  t.it("discard confirmation includes repo/path and cancel leaves all bytes", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(actions, ctx)
        install()
        local prompt
        vim.fn.confirm = function(value) prompt = value; return 2 end
        actions.discard_hunk(ctx)
        t.assert_true(vim.wait(5000, function() return prompt ~= nil end, 10))
        t.assert_contains(prompt, f.root)
        t.assert_contains(prompt, f.path)
        t.assert_eq(f.read(), "new\n")
      end)
    end)
  end)
  t.it("discard rechecks disk after confirmation", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(actions, ctx)
        install()
        vim.fn.confirm = function() f.write("external\n"); return 1 end
        actions.discard_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Working file changed")
        t.assert_eq(f.read(), "external\n")
      end)
    end)
  end)
  t.it("no-final-newline is rejected without manufacturing a newline", function()
    fixture.with_repo(function(f)
      f.baseline("old")
      f.write("new")
      fixture.with_actions(f, "old", f.read(), { replacement }, function(actions, ctx)
        install()
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "No final newline")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old")
        t.assert_eq(f.read(), "new")
      end)
    end)
  end)
  t.it("confirmed discard preserves CRLF and the second hunk", function()
    fixture.with_repo(function(f)
      f.baseline("old\r\nkeep\r\ntail\r\n")
      f.write("new\r\nkeep\r\nother\r\n")
      fixture.with_actions(f, "old\r\nkeep\r\ntail\r\n", f.read(), { replacement }, function(actions, ctx)
        install()
        actions.discard_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Discarded hunk")
        t.assert_eq(f.read(), "old\r\nkeep\r\nother\r\n")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\r\nkeep\r\ntail\r\n")
      end)
    end)
  end)
  t.it("pure EOF deletion can be staged from the remaining last line", function()
    fixture.with_repo(function(f)
      f.baseline("keep\nremove\n")
      f.write("keep\n")
      fixture.with_actions(f, "keep\nremove\n", f.read(), {
        { original = { start_line = 2, end_line = 3 }, modified = { start_line = 2, end_line = 2 } },
      }, function(actions, ctx)
        install()
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Staged hunk")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "keep\n")
      end)
    end)
  end)
  t.it("whole-file stage/restore/delete refuse a dirty buffer", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(_, _, _, _, b)
        install()
        vim.api.nvim_buf_set_lines(b, 0, -1, false, { "UNSAVED" })
        local git = require("codediff.core.git")
        for _, name in ipairs({ "stage_file", "unstage_file", "restore_file", "delete_untracked" }) do
          local err
          git[name](f.root, f.path, function(value) err = value end)
          t.assert_contains(err, "Unsaved buffer")
          t.assert_eq(f.read(), "new\n")
          t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\n")
        end
        for _, name in ipairs({ "stage_all", "unstage_all" }) do
          local err
          git[name](f.root, function(value) err = value end)
          t.assert_contains(err, "Unsaved buffer")
        end
      end)
    end)
  end)
  t.it("native whole-file discard confirms repo/path and cancellation is inert", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function()
        install()
        local prompt
        vim.fn.confirm = function(value) prompt = value; return 2 end
        local explorer = { data = { git_root = f.root } }
        local tree = { get_node = function() return { data = { type = "file", path = f.path, group = "unstaged", status = "M" } } end }
        require("codediff.ui.explorer.actions").restore_entry(explorer, tree)
        t.assert_contains(prompt, f.root)
        t.assert_contains(prompt, f.path)
        t.assert_eq(f.read(), "new\n")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\n")
      end)
    end)
  end)
  t.it("historical comparisons reject hunk and whole-file mutations", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(actions, ctx, session)
        install()
        session.original_revision = "HEAD~1"
        session.panel = { name = "explorer", data = { base_revision = "HEAD~1" } }
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "requires Index/Working")
        local err
        require("codediff.core.git").stage_file(f.root, f.path, function(value) err = value end)
        t.assert_contains(err, "Historical comparison is read-only")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\n")
      end)
    end)
  end)
  t.it("default status accepts resolved HEAD hash and refreshes explicitly", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(actions, ctx, session)
        install()
        session.original_revision = vim.trim(f.git({ "rev-parse", "HEAD" }))
        session.panel = { name = "explorer", data = {} }
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Staged hunk")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "new\n")
        t.assert_true(f.refreshes[1].index)
      end)
    end)
  end)
  t.it("staged-only HEAD view accepts resolved hash and keeps working bytes", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      f.git({ "add", "--", f.path })
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(actions, ctx, session)
        install()
        session.original_revision = vim.trim(f.git({ "rev-parse", "HEAD" }))
        session.modified_revision = ":0"
        session.panel = { name = "explorer", data = { base_revision = session.original_revision, source_revisions = { original = "HEAD", modified = ":0" } } }
        actions.unstage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Unstaged hunk")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\n")
        t.assert_eq(f.read(), "new\n")
      end)
    end)
  end)
  t.it("hunk mutation remains busy until the Git apply callback completes", function()
    fixture.with_repo(function(f)
      f.baseline("base\n")
      f.write("insert\nbase\n")
      fixture.with_actions(f, "base\n", f.read(), {
        { original = { start_line = 1, end_line = 1 }, modified = { start_line = 1, end_line = 2 } },
      }, function(actions, ctx)
        local git = require("codediff.core.git")
        local apply = git.apply_patch
        local pending = {}
        -- Hold submission at the async boundary while preserving real checks
        -- and the real Git operation when released below.
        git.apply_patch = function(...) pending[#pending + 1] = { ... } end
        install()
        actions.stage_hunk(ctx)
        t.assert_true(vim.wait(5000, function() return #pending == 1 end, 10))
        actions.stage_hunk(ctx)
        t.assert_true(vim.wait(5000, function() return #pending > 1 or #f.messages > 0 end, 10))
        local submitted = #pending
        for _, args in ipairs(pending) do apply(unpack(args)) end
        t.assert_true(vim.wait(5000, function()
          for _, message in ipairs(f.messages) do if message:find("Staged hunk", 1, true) then return true end end
        end, 10))
        git.apply_patch = apply
        t.assert_eq(submitted, 1, "a second insertion must not pass preflight while the first write is pending")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "insert\nbase\n")
        f.messages = {}
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Index changed", "completed apply releases busy and runs fresh validation")
      end)
    end)
  end)
  t.it("failed Git apply releases the hunk guard for a retry", function()
    fixture.with_repo(function(f)
      f.baseline("old\n")
      f.write("new\n")
      fixture.with_actions(f, "old\n", f.read(), { replacement }, function(actions, ctx)
        install()
        local lock_path = f.root .. "/.git/index.lock"
        local lock = assert(io.open(lock_path, "wb")); lock:close()
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Failed to stage hunk")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "old\n")
        assert(vim.fn.delete(lock_path) == 0)
        f.messages = {}
        actions.stage_hunk(ctx)
        await(f)
        t.assert_contains(f.messages[1], "Staged hunk")
        t.assert_eq(f.git({ "show", ":0:" .. f.path }), "new\n")
      end)
    end)
  end)
  if require("utils.platform").is_windows then
    t.it("dirty protection resolves real Windows case and short-path aliases", function()
      fixture.with_repo(function(f)
        f.baseline("old\n")
        fixture.with_actions(f, "old\n", f.read(), { replacement }, function(_, _, _, _, buf)
          vim.api.nvim_buf_set_lines(buf, 0, -1, false, { "UNSAVED" })
          local safety = require("workarounds.codediff.safe_mutations")
          t.assert_contains(safety.dirty(f.root:upper(), f.path:upper()), "Unsaved buffer")
          t.assert_contains(safety.dirty(vim.fn.fnamemodify(f.root, ":8"), f.path), "Unsaved buffer")
        end)
      end)
    end)
  end
end)
