local t = require("tests.harness")
t.bootstrap()
local probe = require("utils.probe")

local function isolated(fn)
  local dir = vim.fn.tempname():gsub("\\", "/")
  vim.fn.mkdir(dir, "p")
  local path = dir .. "/probes.json"
  probe._set_path_for_test(path)
  local ok, err = xpcall(function() fn(path, dir) end, debug.traceback)
  probe._set_path_for_test(nil)
  vim.fn.delete(dir, "rf")
  if not ok then error(err) end
end

t.describe("probe feedback acceptance", function()
  t.it("a new repair revision opens observation but the same revision cannot silently renew it", function()
    isolated(function(path)
      probe.record("repair", "old-failure", { state = "unavailable" })
      probe.sleep("repair")
      t.assert_false(probe.is_armed("repair"))
      probe.observe("repair", "revision-a", { days = 7 })
      t.assert_true(probe.is_armed("repair"))
      t.assert_true(probe.record("repair", "new-failure", { state = "unavailable" }))
      probe.sleep("repair")
      probe.observe("repair", "revision-a", { days = 7 })
      t.assert_false(probe.is_armed("repair"), "same repair must respect an ended observation window")
      probe._flush_for_test()
      probe._set_path_for_test(path)
      probe.observe("repair", "revision-a")
      t.assert_false(probe.is_armed("repair"))
      probe.observe("repair", "revision-b")
      t.assert_true(probe.is_armed("repair"))
      t.assert_eq(probe.status("repair").observation.revision, "revision-b")
    end)
  end)

  t.it("reading and resolving evidence are separate and a recurrence reopens the finding", function()
    isolated(function()
      probe.observe("repair", "revision-a")
      probe.record("repair", "failure", { state = "unavailable" })
      t.assert_eq(probe.pending_summary().unread, 1)
      probe.acknowledge("repair", "failure")
      t.assert_eq(probe.pending_summary().unread, 0)
      t.assert_eq(probe.pending_summary().unresolved, 1)
      probe.resolve("repair", "failure", "fixed and fixture verified")
      t.assert_eq(probe.pending_summary().unresolved, 0)
      probe.record("repair", "failure", { state = "unavailable" })
      t.assert_eq(probe.pending_summary().unread, 1)
      t.assert_eq(probe.pending_summary().unresolved, 1)
    end)
  end)

  t.it("historical capacity cannot immediately put a new repair observation back to sleep", function()
    isolated(function(path)
      probe.arm("repair", { max_records = 1 })
      probe.record("repair", "old", { state = "unavailable" })
      probe.sleep("repair")
      probe.observe("repair", "revision-new")
      t.assert_true(probe.record("repair", "new", { state = "unavailable" }))
      t.assert_true(probe.is_armed("repair"))
      probe._flush_for_test()
      local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
      t.assert_eq(vim.tbl_count(disk.topics.repair.records), 1)
      t.assert_true(disk.topics.repair.records.new ~= nil)
      probe._set_path_for_test(path)
      t.assert_true(probe.is_armed("repair"))
    end)
  end)

  t.it("disposition commands persist their distinct decisions and report only marks evidence read", function()
    isolated(function(path)
      probe.setup()
      probe.record("commands", "first", { state = "unavailable" })
      probe.record("commands", "second", { state = "unavailable" })
      local source_window = vim.api.nvim_get_current_win()
      vim.cmd("UEProbeReport")
      local report_window = vim.api.nvim_get_current_win()
      t.assert_eq(probe.pending_summary().unread, 0)
      t.assert_eq(probe.pending_summary().unresolved, 2)
      if report_window ~= source_window then vim.api.nvim_win_close(report_window, true) end
      vim.cmd("UEProbeResolve commands first fixed-by-fixture")
      vim.cmd("UEProbeDefer commands second waiting-for-live-observation")
      probe._flush_for_test()
      local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
      t.assert_eq(disk.topics.commands.records.first.disposition.status, "resolved")
      t.assert_eq(disk.topics.commands.records.second.disposition.status, "deferred")
      t.assert_eq(probe.pending_summary().unresolved, 1)
    end)
  end)

  t.it("a versioned observation preserves its overflow evidence at the storage cap", function()
    isolated(function(path)
      probe.arm("repair", { max_records = 1 })
      probe.observe("repair", "revision-a")
      probe.record("repair", "one")
      t.assert_false(probe.record("repair", "two"))
      probe._flush_for_test()
      local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
      t.assert_true(disk.topics.repair.records._overflow ~= nil)
      t.assert_eq(disk.topics.repair.records._overflow.revision, "revision-a")
    end)
  end)

  t.it("outcome and latency aggregates retain all samples without storing an event list", function()
    isolated(function(path)
      probe.observe("repair", "revision-a")
      for i = 1, 1000 do
        probe.record("repair", "action", { state = i == 1000 and "unavailable" or "resolved", elapsed_ms = i })
      end
      probe._flush_for_test()
      local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
      local record = disk.topics.repair.records.action
      t.assert_eq(record.stats.samples, 1000)
      t.assert_eq(record.stats.total_ms, 500500)
      t.assert_eq(record.stats.max_ms, 1000)
      t.assert_eq(record.stats.outcomes.resolved, 999)
      t.assert_eq(record.stats.outcomes.unavailable, 1)
      t.assert_true(vim.tbl_count(record.stats.buckets) <= 5)
      t.assert_eq(record.revision, "revision-a")
      t.assert_true(vim.uv.fs_stat(path).size < 4096)
    end)
  end)

  t.it("successful observations neither create failures nor reopen an already resolved failure", function()
    isolated(function()
      probe.record("actions", "outcome", { state = "resolved", elapsed_ms = 4 })
      t.assert_eq(probe.pending_summary().unresolved, 0)
      probe.record("actions", "outcome", { state = "unavailable", elapsed_ms = 5 })
      t.assert_eq(probe.pending_summary().unresolved, 1)
      probe.resolve("actions", "outcome", "failure verified fixed")
      probe.record("actions", "outcome", { state = "resolved", elapsed_ms = 6 })
      t.assert_eq(probe.pending_summary().unresolved, 0)
    end)
  end)

  t.it("normal process exit preserves a new failure even without command setup", function()
    isolated(function(path, dir)
      local script = dir .. "/exit.lua"
      vim.fn.writefile({
        "vim.opt.rtp:prepend(" .. vim.inspect(vim.fn.stdpath("config")) .. ")",
        "local p = require('utils.probe')",
        "p._set_path_for_test(" .. vim.inspect(path) .. ")",
        "p.record('exit', 'failure', {state='unavailable'})",
        "vim.cmd('qa!')",
      }, script)
      local result = vim.system({ vim.v.progpath, "--headless", "-u", "NONE", "-l", script }, { text = true }):wait(10000)
      t.assert_eq(result.code, 0, result.stderr)
      t.assert_eq(vim.fn.filereadable(path), 1, "normal exit lost pending evidence")
      local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
      t.assert_eq(disk.topics.exit.records.failure.count, 1)
    end)
  end)

  t.it("a failed publication keeps pending evidence and retries after the storage recovers", function()
    isolated(function(path)
      local store = require("utils.probe_store")
      local original = store.save
      local ok, err = xpcall(function()
        probe.record("retry", "failure", { state = "unavailable" })
        store.save = function() return false, "injected EIO" end
        probe._flush_for_test()
        t.assert_true(probe._has_pending_save_for_test())
        t.assert_contains(probe.status("retry").storage_error, "EIO")
        store.save = original
        t.assert_true(vim.wait(2000, function() return vim.fn.filereadable(path) == 1 end, 20))
        local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
        t.assert_eq(disk.topics.retry.records.failure.count, 1)
        t.assert_nil(probe.status("retry").storage_error)
      end, debug.traceback)
      store.save = original
      if not ok then error(err) end
    end)
  end)

  t.it("concurrent writers merge aggregates and an old acknowledgement cannot hide a new failure", function()
    isolated(function(path)
      probe.observe("repair", "revision-a")
      probe.record("repair", "action", { state = "resolved", elapsed_ms = 5 })
      probe._flush_for_test()
      local module = vim.fn.stdpath("config") .. "/lua/utils/probe.lua"
      local left, right = assert(loadfile(module))(), assert(loadfile(module))()
      left._set_path_for_test(path)
      right._set_path_for_test(path)
      left.status("repair")
      right.status("repair")
      local ok, err = xpcall(function()
        left.record("repair", "action", { state = "resolved", elapsed_ms = 10 })
        right.record("repair", "action", { state = "unavailable", elapsed_ms = 20 })
        left._flush_for_test()
        right._flush_for_test()
        left.resolve("repair", "action", "older observation verified")
        left._flush_for_test()
        local disk = vim.json.decode(table.concat(vim.fn.readfile(path), "\n"))
        local record = disk.topics.repair.records.action
        t.assert_eq(record.count, 3)
        t.assert_eq(record.stats.samples, 3)
        t.assert_eq(record.stats.total_ms, 35)
        t.assert_eq(record.stats.outcomes.resolved, 2)
        t.assert_eq(record.stats.outcomes.unavailable, 1)
        probe._set_path_for_test(path)
        t.assert_eq(probe.pending_summary().unresolved, 1)
        t.assert_eq(probe.pending_summary().unread, 1)
      end, debug.traceback)
      left._set_path_for_test(nil)
      right._set_path_for_test(nil)
      if not ok then error(err) end
    end)
  end)
end)
