-- tests/cases/ue_config_spec.lua
-- ue.config schema：默认值、setup() override、reset_for_test() 恢复。

local t = require("tests.harness")
t.bootstrap()

t.describe("ue.config: 默认值", function()
  local cfg = require("ue.config")

  t.it("index.idle_cold_ms == 120000", function()
    t.assert_eq(cfg.get("index.idle_cold_ms"), 120000)
  end)
  t.it("context.ttl_s == 30", function()
    t.assert_eq(cfg.get("context.ttl_s"), 30)
  end)
  t.it("paths.state_dir 含 'ue'", function()
    local p = cfg.get("paths.state_dir")
    t.assert_true(p and p:find("ue") ~= nil, "state_dir 应含 ue")
  end)
  t.it("未知键返回 nil", function()
    t.assert_nil(cfg.get("does.not.exist"))
  end)
  t.it("options() 含 clangd/dap/cdb 表", function()
    local opts = cfg.options()
    t.assert_type(opts.clangd, "table", "clangd 缺失")
    t.assert_type(opts.dap, "table", "dap 缺失")
    t.assert_type(opts.cdb, "table", "cdb 缺失")
  end)
  t.it("cdb.steps 默认 5 项", function()
    t.assert_eq(#cfg.get("cdb.steps"), 5)
  end)
  t.it("cdb.tools_dir 是 string", function()
    t.assert_type(cfg.get("cdb.tools_dir"), "string")
  end)
  t.it("dap.lldb_dap_path 默认 nil", function()
    t.assert_nil(cfg.get("dap.lldb_dap_path"))
  end)
end)

t.describe("ue.config: override 与 reset", function()
  local cfg = require("ue.config")

  t.it("setup 覆盖后 reset_for_test 恢复 (index)", function()
    cfg.setup({ index = { idle_cold_ms = 99 } })
    t.assert_eq(cfg.get("index.idle_cold_ms"), 99)
    cfg.reset_for_test()
    t.assert_eq(cfg.get("index.idle_cold_ms"), 120000)
  end)

  t.it("setup 覆盖后 reset_for_test 恢复 (dap)", function()
    cfg.setup({ dap = { lldb_dap_path = "/x/lldb-dap" } })
    t.assert_eq(cfg.get("dap.lldb_dap_path"), "/x/lldb-dap")
    cfg.reset_for_test()
    t.assert_nil(cfg.get("dap.lldb_dap_path"))
  end)
end)
