-- ue.cdb.paths — locate compile_commands.json on disk.
--
-- Phase E.2: lift the path-resolution helpers out of `ue.lua`.

local fs = require("ue.core.fs")

local M = {}

--- Canonical compile_commands.json target for the active project/session.
--- New contexts write only inside their project+platform cache bucket so two
--- Neovim processes cannot overwrite each other's active CDB. The two legacy
--- engine-root targets remain only for callers that do not provide ctx.paths.
---@param ctx { engine_root: string, paths?: { active_cdb?: string } }
---@return string[]
function M.targets(ctx)
  if ctx.paths and ctx.paths.active_cdb and ctx.paths.active_cdb ~= "" then
    return { fs.norm(ctx.paths.active_cdb) }
  end
  return {
    fs.join(ctx.engine_root, "compile_commands.json"),
    fs.join(ctx.engine_root, "Engine", "compile_commands.json"),
  }
end

local function tuple_segment(value)
  value = tostring(value or ""):gsub("^%s+", ""):gsub("%s+$", "")
  value = value:gsub("[^%w_.%-]+", "_")
  return value ~= "" and value or "unknown"
end

--- Stable, tuple-owned source generated by an explicit semantic compile task.
--- This is input to :UEPrepare, not clangd's canonical published database.
---@param ctx { engine_root: string, paths?: { cache?: string } }
---@param tuple { platform?: string, target?: string, configuration?: string }
---@return string
function M.semantic_source(ctx, tuple)
  tuple = tuple or {}
  local cache = ctx.paths and ctx.paths.cache
    or fs.join(ctx.engine_root, ".cache", "nvim-ue")
  local key = table.concat({
    tuple_segment(tuple.platform or tuple.target_platform),
    tuple_segment(tuple.target),
    tuple_segment(tuple.configuration),
  }, "-")
  return fs.join(cache, "cdb", "sources", key, "compile_commands.json")
end

--- Discover readable compile_commands.json files only at controlled locations.
--- Recursive discovery is intentionally forbidden: UE vendors third-party test
--- fixtures named compile_commands.json, and one of those used to be promoted
--- to the engine root as if it described the active target.
---@param ctx { engine_root: string, project_root?: string }
---@param deps? { tuple?: table }
---@return string[]
function M.candidates(ctx, deps)
  deps = deps or {}

  local seen = {}
  local out = {}
  local function add(path)
    path = fs.norm(path)
    if path ~= "" and not seen[path] and fs.is_file(path) then
      seen[path] = true
      table.insert(out, path)
    end
  end

  -- The tuple-scoped semantic source is the producer-owned input.  Canonical
  -- files are derived clangd mirrors and may still describe the previous
  -- build, so they must never shadow a freshly generated source.
  if deps.tuple then add(M.semantic_source(ctx, deps.tuple)) end
  for _, target in ipairs(M.targets(ctx)) do add(target) end
  -- Engine/project copies are inputs only. They may be emitted by UBT or an
  -- older nvim-ue version, but are never canonical write targets now.
  add(fs.join(ctx.engine_root, "compile_commands.json"))
  add(fs.join(ctx.engine_root, "Engine", "compile_commands.json"))
  if ctx.project_root and ctx.project_root ~= "" then
    add(fs.join(ctx.project_root, "compile_commands.json"))
  end
  add(fs.join(ctx.engine_root, "Engine", "Intermediate", "Build", "compile_commands.json"))

  return out
end

return M
