#!/usr/bin/env python3
"""
prebuild_pch.py — 为 clangd 预编译 SharedPCH 头文件

生成一个 PowerShell 脚本来在 Windows 上编译 PCH，
然后修改 compile_commands.json 替换 -include -> -include-pch

使用步骤:
  1. python prebuild_pch.py <PROJ_DRIVE>/UEProj/compile_commands.json
     -> 生成 build_pch.ps1 + 修改 compile_commands.json
  2. 在 PowerShell 中执行 build_pch.ps1
  3. 在 .clangd 中去掉 Remove: -include-pch
  4. 重启 clangd
"""

import json
import os
import re
import shutil
import sys
from collections import defaultdict
from pathlib import Path


def extract_pch_groups(entries):
    groups = defaultdict(lambda: {"indices": [], "sample_args": None})
    for i, e in enumerate(entries):
        args = e.get("arguments", [])
        for j, a in enumerate(args):
            if a == "-include" and j + 1 < len(args):
                nxt = args[j + 1].replace("\\", "/")
                if "SharedPCH." in nxt or "/PCH." in nxt:
                    key = args[j + 1]  # 保持原始路径
                    groups[key]["indices"].append(i)
                    if groups[key]["sample_args"] is None:
                        groups[key]["sample_args"] = args[:]
                    break
    return groups


def extract_compile_flags(args):
    """从 compile_commands 参数提取编译 PCH 需要的选项"""
    flags = []
    skip_next = False
    for i, a in enumerate(args):
        if skip_next:
            skip_next = False
            continue
        # 跳过不需要的
        if a in ("-c", "-o", "-MF", "-MT", "-MQ", "-MD", "-MMD",
                  "-Werror", "-fdiagnostics-format", "-no-canonical-prefixes"):
            if a in ("-o", "-MF", "-MT", "-MQ"):
                skip_next = True
            continue
        if a.startswith("-o") and len(a) > 2:
            continue
        # 跳过源文件（最后一个参数）
        if i == len(args) - 1 and (a.endswith(".cpp") or a.endswith(".c")):
            continue
        # 跳过 -include (我们在末尾单独处理 PCH 头)
        if a == "-include":
            skip_next = True
            continue
        # 跳过编译器路径（第一个参数）
        if i == 0:
            continue
        flags.append(a)
    return flags


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <compile_commands.json> [--dry-run]")
        sys.exit(1)

    cc_path = os.path.abspath(sys.argv[1])
    dry_run = "--dry-run" in sys.argv

    with open(cc_path) as f:
        data = json.load(f)

    groups = extract_pch_groups(data)
    print(f"条目: {len(data)}, SharedPCH 种类: {len(groups)}")

    if not groups:
        print("没有 SharedPCH 条目")
        return

    cc_dir = os.path.dirname(cc_path)
    # PCH 输出目录用 Windows 路径
    pch_dir_wsl = os.path.join(cc_dir, ".clangd-pch")
    os.makedirs(pch_dir_wsl, exist_ok=True)

    # 推断 Windows 路径
    # <PROJ_DRIVE>/UEProj -> <PROJ_DRIVE>/UEProj
    if cc_dir.startswith("/mnt/"):
        drive = cc_dir[5].upper()
        pch_dir_win = f"{drive}:{cc_dir[6:]}/.clangd-pch".replace("/", "\\")
    else:
        pch_dir_win = pch_dir_wsl.replace("/", "\\")

    # 生成 PowerShell 编译脚本
    ps1_lines = [
        '# Auto-generated by prebuild_pch.py',
        '# Run this in PowerShell to compile PCH files for clangd',
        f'$pchDir = "{pch_dir_win}"',
        '$clang = "C:\\Program Files\\LLVM\\bin\\clang++.exe"',
        'if (-not (Test-Path $pchDir)) { New-Item -ItemType Directory -Path $pchDir | Out-Null }',
        '$sw = [System.Diagnostics.Stopwatch]::StartNew()',
        '',
    ]

    pch_map = {}  # original_header -> pch_path (Windows)

    for pch_header, info in sorted(groups.items(), key=lambda x: -len(x[1]["indices"])):
        basename = Path(pch_header.replace("\\", "/")).stem
        pch_output_win = f"{pch_dir_win}\\{basename}.pch"

        print(f"  {len(info['indices']):5d} files  {basename}")

        # 提取编译选项
        flags = extract_compile_flags(info["sample_args"])

        # 构建 clang 命令
        # 关键: -x c++-header 告诉 clang 这是头文件要生成 PCH
        flag_str = " ".join(f'"{f}"' if " " in f else f for f in flags)
        pch_header_escaped = pch_header.replace("\\", "\\\\")

        ps1_lines.append(f'Write-Output "Building {basename}.pch ({len(info["indices"])} files)..."')
        ps1_lines.append(f'& $clang {flag_str} -x c++-header -Wno-everything -o "{pch_output_win}" "{pch_header}"')
        ps1_lines.append(f'if ($LASTEXITCODE -eq 0) {{ Write-Output "  OK: $(((Get-Item \"{pch_output_win}\").Length / 1MB).ToString(\"0.0\")) MB" }} else {{ Write-Output "  FAILED" }}')
        ps1_lines.append('')

        pch_map[pch_header] = pch_output_win

    ps1_lines.append('$sw.Stop()')
    ps1_lines.append('Write-Output "Total: $($sw.Elapsed.TotalSeconds.ToString(\"0.0\"))s"')

    ps1_path_wsl = os.path.join(cc_dir, "build_pch.ps1")
    with open(ps1_path_wsl, "w", encoding="utf-8") as f:
        f.write("\n".join(ps1_lines))

    print(f"\nPS1 脚本: {ps1_path_wsl}")

    if dry_run:
        print("(dry-run) 不修改 compile_commands.json")
        return

    # 修改 compile_commands: -include X.h -> -include-pch X.pch
    modified = 0
    for pch_header, pch_path_win in pch_map.items():
        for idx in groups[pch_header]["indices"]:
            args = data[idx]["arguments"]
            new_args = []
            skip_next = False
            for i, a in enumerate(args):
                if skip_next:
                    skip_next = False
                    continue
                if a == "-include" and i + 1 < len(args):
                    if args[i + 1] == pch_header:
                        new_args.append("-include-pch")
                        new_args.append(pch_path_win)
                        skip_next = True
                        modified += 1
                        continue
                new_args.append(a)
            data[idx]["arguments"] = new_args

    bak = cc_path + ".pre-pch.bak"
    if not os.path.exists(bak):
        shutil.copy2(cc_path, bak)

    with open(cc_path, "w") as f:
        json.dump(data, f, ensure_ascii=False)

    # 同步到 Engine 子目录
    engine_cc = os.path.join(cc_dir, "Engine", "compile_commands.json")
    if os.path.exists(os.path.dirname(engine_cc)):
        shutil.copy2(cc_path, engine_cc)
        print(f"同步: {engine_cc}")

    print(f"\n替换了 {modified} 个条目")
    print(f"\n下一步:")
    print(f"  1. 在 PowerShell 中运行: {ps1_path_wsl.replace('/mnt/d','D:').replace('/','\\\\')}")
    print(f"  2. 在 .clangd 中去掉 Remove: -include-pch")
    print(f"  3. 重启 Neovim/clangd")


if __name__ == "__main__":
    main()
